config:
  open-ai:
    url: https://api.openai.com/v1/chat/completions
    api-key: ${OPEN_AI_KEY}
    model: gpt-3.5-turbo

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /callback
