config:
  open-ai:
    url: https://api.openai.com/v1/chat/completions
    api-key: ${OPEN_AI_KEY}
    model: gpt-3.5-turbo
    message: "{\"role\": \"system\", \"content\": \"返答は日本語で\"},{\"role\": \"user\", \"content\": \" + preMessage + \"}"

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /callback
